### ISSUE TITLE
Option to show only Sidebar or Panel at a time.

### ISSUE THREAD

**Issue by cuongthm** [sirmspencer/vscode-autohide#1]
Hello.

Please add option to show only Sidebar or Panel at a time (auto close other one if it was opened).
Because I were set both of them's position to one right side, so I want to open just only one at a time.

Thanks for this useful extension.

**Comment by sirmspencer** [comment]
It will all depend on if VS Code provides and event for those when they open. I dont think they do.

If you are using keyboard shortcuts to open the sidebar and panel, you could create a custom keyboard shortcut function that fires the actions you are looking for.

**Comment by sirmspencer** [comment]
There is no event to say that the panel or sidebar opened.  You will need to create your own keybindings to do this.
