### ISSUE TITLE
Just won't work until I change the file

### ISSUE THREAD

**Issue by siathalysedI** [sirmspencer/vscode-autohide#11]
I installed and configured but it does not work. It just works when I change the file

**Comment by siathalysedI** [comment]
https://gifyu.com/image/4wbP

**Comment by sirmspencer** [comment]
There is no native support for autohiding, this is a bit of a hack.  The only action available is "selectionChange" so the selection inside each file has to actually change to trigger the event.  It wont work in empty files or extension descriptions.
