### ISSUE TITLE
Request: disable during debugging

### ISSUE THREAD

**Issue by morgan-256** [sirmspencer/vscode-autohide#12]
Would be great to have the extension not autohide during debugging as this is when sidebar/terminal are very important. Great extension though, thank you!

**Comment by sirmspencer** [comment]
I'll look into it if I have time. https://stackoverflow.com/questions/42397699/detect-debug-mode-in-vscode-extension

The other option is to use the pin commands provided, that enable and disable the autohide, to a keyboard shortcut.  Let me know if the README is not sufficuant.

**Comment by anonymous1184** [comment]
Hello!

Any update on this request? Seems like a really great idea since most of the time is either coding (this hiding is needed) or debuging (meaning you need the side bar and panels) and having to toggle everything before after gets old pretty quick.

**Comment by ylazy** [comment]
Same issue.

**Comment by sirmspencer** [comment]
There should already be a keyboard shortcut to disable.  I dont have any plans to add this as an extra feature.
