### ISSUE TITLE
Clicking on the sideBar/panel should reset the panel Delay 

### ISSUE THREAD

**Issue by akulmehta** [sirmspencer/vscode-autohide#14]
I have increased the time in the sideBarDelay and paneldelay options to be 10s (10000). The reason is I do not want the panels to auto-hide immediately as I often see a file and then decide maybe I need to see another file. As a result I stumbled upon an issue. 

If we have the sideBar open and then click on the text editor it starts the countdown for the delay. However, then if we click on the sideBar the countdown still continues and if you are seeing something in the sideBar suddenly when the countdown delay reaches 0 it closes. I was hoping that when we click on the sideBar or the panel then the countdown should reset and not be triggered.

**Steps to reproduce:**
1. Set the `autoHide.autoHidePanel` and the `autoHide.sideBarDelay` to `10000` ms.
2. Open the sidebar or terminal. 
3. Click on the text editor (this will start the delay `setTimeout` functions and lets call this T1). Immediately, click on the sidebar or the terminal within 10s. 
4. When the setTimeout T1 expires it will close the sidebar/terminal

**Desired Change**
When you click on the sidebar or the terminal the `setTimeout` should be cleared.

**Comment by sirmspencer** [comment]
I see what you are asking for, but I dont think there is an event I can tie into to make that happen. Ill look a minute before I close this.

**Comment by akulmehta** [comment]
Thanks @sirmspencer I understand the difficulty too. I forked the repo in order to contribute but couldn't find an event listener in the VS Code API for it too. Just an idea to keep in mind for the time being I suppose.

**Comment by sirmspencer** [comment]
Unfortunately, this just isnt the behavior I designed for and I dont really have any motivation to change the default behavior.
