### ISSUE TITLE
Show side bar on hovering the activity bar

### ISSUE THREAD

**Issue by martin-braun** [sirmspencer/vscode-autohide#17]
Hi, first of all thank you for making this. [This feature is still not implemented](https://github.com/Microsoft/vscode/issues/3742), so I really appreciate your effort in doing this.

The only thing that bugs me a lot is the fact that I have to click the small icon or use the hotkey to show the side bar, again. I would love to show it on hovering the activity bar. I know this is a duplicate of #13, but I think only this particular issue can be solved pretty quickly. Additionally, a timeout delay setting for that behavior would be nice, but I think it would already be a good upgrade to have a simple instant show on hover available.

**Comment by sirmspencer** [comment]
There is currently no events for hovering over a button.  This is beyond the ability of a plug in to fix.

**Comment by martin-braun** [comment]
@sirmspencer Thank you for the quick response. I thought about some alternatives and ended up to use BetterTouchTool to assign the double finger tab gesture on my trackpad to the hotkey to show the side bar. Not a fix for everyone, but at least a solution for me.

Maybe the hover event will be provided before the actual feature comes, though.

**Comment by martin-braun** [comment]
I guess your conclusion is the necessary API will never come, right?
