### ISSUE TITLE
Settings changes don't take effect until VS Code reload

### ISSUE THREAD

**Issue by mterrel** [sirmspencer/vscode-autohide#2]
I was trying to use VS Code settings to set `autoHidePanel` to `false`, but the panel was still auto hiding. I eventually figured out that I had to restart VS Code for the setting change to take effect.

I'm using Auto Hide version 1.0.3

**Comment by sirmspencer** [comment]
Thanks, Ill look into it.

**Comment by sirmspencer** [comment]
This is fixed in 1.0.4
