### ISSUE TITLE
Sidebar visible when using multiple panels and switching

### ISSUE THREAD

**Issue by lalilaloe** [sirmspencer/vscode-autohide#22]
I have some weird behavior if i use split panels for showing 2 files next to eachother. See gif for example.

- When i click on the non-active panel, the sidebar shows, it only shows briefly
- If you click on the non-active panel, for example the left and accidentally hover above the sidebar it stays open. You have to click again for it to autohide

![autohidesidebar](https://user-images.githubusercontent.com/9057622/186429144-85d54190-2136-4f16-8e69-c91e73431673.gif)

**Comment by sirmspencer** [comment]
Yup, that is how the events work.  I recommend moving your panel to the right side to reduce the awkwardness.
