### ISSUE TITLE
Feature: Dynamically enable based on window size (laptop vs external etc)

### ISSUE THREAD

**Issue by globalhuman** [sirmspencer/vscode-autohide#24]
Problem: 

I only want to enable autohide when I'm working on a small screen (laptop). When I'm on a big screen (external) I have ample room to leave the side bar open.

Proposed Solution: 

Add a configuration that depending on the size of the window (and scaling) enables/disables autohide.

**Comment by sirmspencer** [comment]
I dont think that information is available.  You can set a keyboard shortcut to enable and disable.
