### ISSUE TITLE
autoHide.sideBarDelay - number values eq ? 

### ISSUE THREAD

**Issue by ajaxStardust** [sirmspencer/vscode-autohide#26]
hi. thank you very much for this extension. I use it a lot. occasionally. sometimes very often. 

I can't figure out how to adjust the time-out to my liking. I don't perceive that changing the values of autoHide.sideBarDelay (e.g. in @ext:sirmspencer.vscode-autohide ) has any perceivable effect on the actual behavior. Do the values represent milliseconds? 

It seems to either basically go away almost immediately (default, which is great if you want that ), or it to never go away if i increase the number but maybe i'm adding too much to it 

What might I be doing wrong? 

I'd very much love having the sidebar go away, except maybe after 5-10 seconds or so 

Thank you muchas gracias!

**Comment by sirmspencer** [comment]
It should be milliseconds.

**Comment by ajaxStardust** [comment]
thank you.
