### ISSUE TITLE
Publish vscode-autohide to Open VSX

### ISSUE THREAD

**Issue by cz4rny** [sirmspencer/vscode-autohide#28]
Dear extension author,
Please publish this extension to the [Open VSX marketplace](https://open-vsx.org/).

## Context

Unfortunately, as Microsoft prohibits usages of the Microsoft marketplace by any other products or redistribution of `.vsix` files from it, in order to use VS Code extensions in non-Microsoft products, we kindly ask that you take ownership of the VS Code extension namespace in [Open VSX](https://open-vsx.org/) and publish this extension on Open VSX.

## What is Open VSX? Why does it exist?

Open VSX is a vendor neutral alternative to the MS marketplace used by most other derivatives of VS Code like [VSCodium](https://vscodium.com/), [Gitpod](https://www.gitpod.io), [OpenVSCode](https://github.com/gitpod-io/openvscode-server), [Theia](https://theia-ide.org/)-based IDEs, and so on.

You can read on about Open VSX at the Eclipse Foundation's [Open VSX FAQ](https://www.eclipse.org/legal/open-vsx-registry-faq/).

## How can you publish to Open VSX?

The docs to publish an extension can be found [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). This process is straightforward and shouldn't take too long. Essentially, you need an authentication token and to execute the `ovsx publish` command to publish your extension. There's also [a doc](https://github.com/open-vsx/publish-extensions/blob/master/docs/direct_publish_setup.md) explaining the whole process with an example GitHub Action workflow.

**Comment by sirmspencer** [comment]
This code is open source.  You are free to make a fork and publish it there.

**Comment by cz4rny** [comment]
Indeed @sirmspencer, I can publish it. But I can't put it into your pipeline so that it gets updated with your new releases. It's better to do it at the source, than externally.

**Comment by sirmspencer** [comment]
I don't really make updates.  This is a one trick pony, and it's already implemented.

**Comment by goyalyashpal** [comment]
really nice issue description template

@cz4rny where did you get that from??

**Comment by cz4rny** [comment]
> where did you get that from??

From the [open-vsx publishing howto](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) — they link to [the template](https://github.com/open-vsx/publish-extensions/blob/master/docs/external_contribution_request.md).
