### ISSUE TITLE
The extension is not keyboard-driven environment friendly

### ISSUE THREAD

**Issue by denis-onder** [sirmspencer/vscode-autohide#3]
Hello there!

Loving the extension, but it seems like it is only reacting to clicks on the editor window.

If you'd use CTRL+Shift+E to focus into the explorer tab and switch to a new file from there, 
even though you start typing and the focus shifted over to the editor window, 
the extension is not noticing the focus shift, hence leaving the sidebar and terminal windows open.

Thanks!

**Comment by sirmspencer** [comment]
There is no internal event in vscode that fires for the keyboard.  It is not possible to close the explorer in that case.  If you are keyboard driven find/create a shortcut to close your explorer tab.

**Comment by MartyBeGood** [comment]
Actually there might be a fix for that:
There are 3 `TextEditorSelectionChangeKind` values: `Mouse`, `Keyboard` and `Command`.

- `Mouse` fires when you click inside an editor
- `Command` fires when a command changes an editor (like when you open a file from the sidebar)
- `Keyboard` fires when you start _typing_ in the editor (moving the cursor or selecting via keyboard is not enough)

If you just want to avoid to close the sidebar when you select anything that might open an editor (like looking through your changes on the git panel file by file), then it's enough to change the first condition in src/extension.ts:17 from `selection.kind != TextEditorSelectionChangeKind.Mouse` to `selection.kind == TextEditorSelectionChangeKind.Command`

I tried it out and I'm happy with it so far. Is there a case where this closes the sidebar when you need it that I missed?

I'd be happy to send you a PR as well :)
