### ISSUE TITLE
Option to just Hide when do a double click into a text editor.

### ISSUE THREAD

**Issue by devdariill** [sirmspencer/vscode-autohide#32]
Some times i dont want activate the auto hide and  the alternative is with a double click and then activate the auto hide.

**Comment by sirmspencer** [comment]
If you can double click, just move your mouse a little as you do and it should hide.

**Comment by devdariill** [comment]
i mean, to just hide when do the double click.

**Comment by sirmspencer** [comment]
Id consider a PR, but I am closing this because I don't think it's necessary and might not be possible.  This works on the text position changed event.  I don't think there is a click inside editor event, and especially not a double click inside editor event.
