### ISSUE TITLE
Makes in the Working tree the popup menu disappears

### ISSUE THREAD

**Issue by crystalfp** [sirmspencer/vscode-autohide#38]
Type: <b>Bug</b>

- Open a Working tree window on a file that has lines changed from the ones in GIT.
- Click on the light bulb on the previous line in a change.
- The popup menu in which you can revert the change briefly appears and immediately disappears

Extension version: 1.0.8
VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:28:19.990Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.77GB (15.81GB free)|
|Process Argv|D:\\Projects\\STMng\\STMng.code-workspace --crash-reporter-id df3b806e-c371-4e03-89b8-d13088946634|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by crystalfp** [comment]
If you disable `autoHide.autoHideReferences` the problem disappears.
Really I don't see a connection between references and revert changes menu.
I suggest at least to document this behavior or fix it.
Thanks!

**Comment by sirmspencer** [comment]
I don't think that's from a default vs code functionality.  I don't see any light bulbs from those steps.

**Comment by crystalfp** [comment]
![image](https://github.com/sirmspencer/vscode-autohide/assets/865866/44eec52b-f3c4-4a31-a8ae-d8f5788cece9)
@sirmspencer How do you call the thingy on line 9? For me it is a light bulb.
The lines are from the working Tree view of a file modified from the Git version.

**Comment by sirmspencer** [comment]
Yeah its a light bulb.  It looks specific to your set up.  I can't replicate so I can't fix.  Feel free to submit a PR if you find something.
