### ISSUE TITLE
Feature request: Auto-hide sidebar and panel on Workspace launch

### ISSUE THREAD

**Issue by ZLevine** [sirmspencer/vscode-autohide#7]
One thing that drives me nuts is if I launch VSCode using a Workspace file, the sidebar and panel reopen if they were opened when you quit. There's no VSCode setting to prevent this, unfortunately.

This would be a great feature—to ensure the panel and sidebar are closed on launch, no matter what.

**Comment by sirmspencer** [comment]
This may be possible, I will look into it.

**Comment by sirmspencer** [comment]
I see what you mean with it being open on relaunch.  Never noticed much before but I really like this suggestion.

**Comment by sirmspencer** [comment]
This is added in 1.0.5, let me know how it works.

**Comment by ZLevine** [comment]
Awesome, tested and works great!

There is a slight flash where you see the panel/sidebar are open (and then they close). It would be great if you never see them open to begin with, but I'm not sure that's possible. Either way, great work :)

**Comment by sirmspencer** [comment]
> Awesome, tested and works great!
> 
> There is a slight flash where you see the panel/sidebar are open (and then they close). It would be great if you never see them open to begin with, but I'm not sure that's possible. Either way, great work :)

You are correct.  The extension closes the panel as soon as its able to.  Not sure if you can get extensions to register in a different order locally.

**Comment by ZLevine** [comment]
Ah yes, I figured as much. No worries.
