### ISSUE TITLE
VSCode Remote compatibility

### ISSUE THREAD

**Issue by Trass3r** [sirmspencer/vscode-autohide#8]
When using the Remote WSL extension this one is disabled on the host side and it is suggested to install it in WSL.
Is that intentional or doesn't this extension properly identify itself as a UI-only extension?
https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location

**Comment by sirmspencer** [comment]
I have not defined "extensionKind".  I do not really know what the difference here is.  I dont think it requires a workspace so it should be UI.  Is it default UI only? It doesnt say.  I wouldnt know how to test that it works specifically in either space, or how it relates to WSL.

Your message may also just mean that you have to resinstall it inside WSL.

**Comment by Trass3r** [comment]
In the remote development scenario plugins are split into UI and non-UI so only the UI runs on the host: https://code.visualstudio.com/docs/remote/remote-overview

**Comment by sirmspencer** [comment]
I dont intend to support WSL.  I you create a PR to fix your issue, I can look at it.

**Comment by Trass3r** [comment]
It should be `"extensionKind": ["ui", "workspace"]` if it makes sense to use it in VSCode Online (which I don't use) and just `[ "ui" ]` otherwise.
